version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
  restaurant:
    image: restaurant:latest
    container_name: restaurant
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: sh -c "alembic upgrade head
      && uvicorn src.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres:
    name: db